current_img_model: gpt-4o
current_model: gemini-2.5-pro-exp-03-25
json_mode: false
models:
  claude-3-5-haiku-latest:
    category: claude
    json_template: detailed
    max_tokens: 4002
    model: claude-3-5-haiku-20240307
    provider: anthropic
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  claude-3-5-sonnet-latest:
    category: claude
    json_template: detailed
    max_tokens: 4000
    model: claude-3-5-sonnet-20240620
    provider: anthropic
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  claude-3-7-sonnet-latest:
    category: claude
    json_template: detailed
    max_tokens: 4000
    model: claude-3-7-sonnet-20250219
    provider: anthropic
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  gemini-1.5-pro:
    category: gemini
    json_template: default
    max_tokens: 4000
    model: gemini-1.5-pro
    provider: google
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  gemini-2.0-flash:
    category: gemini
    json_template: default
    max_tokens: 4000
    model: gemini-2.0-flash
    provider: google
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  gemini-2.0-flash-lite:
    category: gemini
    json_template: default
    max_tokens: 4000
    model: gemini-2.0-flash-lite
    provider: google
    supports_system_prompt: true
    system_prompt_key: default_system
    temperature: 0.7
  gemini-2.0-flash-thinking-exp:
    category: gemini
    json_template: default
    max_tokens: 4000
    model: gemini-2.0-flash-thinking-exp
    provider: google
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  gemini-2.5-pro-exp-03-25:
    category: gemini
    json_template: default
    max_tokens: 4000
    model: gemini-2.5-pro-exp-03-25
    provider: google
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  gpt-4:
    category: gpt
    json_template: default
    max_tokens: 4000
    model: gpt-4
    provider: openai
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  gpt-4.5:
    category: gpt
    json_template: default
    max_tokens: 4000
    model: gpt-4.5-preview
    provider: openai
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  gpt-4o:
    category: gpt
    json_template: default
    max_tokens: 4000
    model: gpt-4o
    provider: openai
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  grok-2-latest:
    category: grok
    json_template: default
    max_tokens: 4000
    model: grok-2-latest
    provider: xai
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  grok-3-latest:
    category: grok
    json_template: default
    max_tokens: 4000
    model: grok-3-latest
    provider: xai
    supports_system_prompt: true
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
  o3-mini:
    category: o3
    json_template: default
    max_tokens: 45000
    model: o3-mini
    provider: openai
    reasoning_effort: high
    supports_system_prompt: false
    system_message: You are a helpful, accurate, and friendly AI assistant.
    system_prompt_key: default_system
    temperature: 0.7
provider_mapping:
  claude-3-5-haiku-latest:
    category: claude
    provider: anthropic
  claude-3-5-sonnet-latest:
    category: claude
    provider: anthropic
  claude-3-7-sonnet-latest:
    category: claude
    provider: anthropic
  gemini-1.5-pro:
    category: gemini
    provider: google
  gemini-2.0-flash:
    category: gemini
    provider: google
  gemini-2.0-flash-lite:
    category: gemini
    provider: google
  gemini-2.0-flash-thinking-exp:
    category: gemini
    provider: google
  gemini-2.5-pro-exp-03-25:
    category: gemini
    provider: google
  gpt-4:
    category: gpt
    provider: openai
  gpt-4.5:
    category: gpt
    provider: openai
  gpt-4o:
    category: gpt
    provider: openai
  grok-2-latest:
    category: grok
    provider: xai
  grok-3-latest:
    category: grok
    provider: xai
  o3-mini:
    category: o3
    provider: openai
providers:
  anthropic:
    claude:
    - claude-3-7-sonnet-latest
    - claude-3-5-haiku-latest
    - claude-3-5-sonnet-latest
  google:
    gemini:
    - gemini-2.0-flash
    - gemini-2.0-flash-lite
    - gemini-1.5-pro
    - gemini-2.0-flash-thinking-exp
    - gemini-2.5-pro-exp-03-25
  openai:
    gpt:
    - gpt-4
    - gpt-4o
    - gpt-4.5
    o3:
    - o3-mini
  xai:
    grok:
    - grok-3-latest
    - grok-2-latest
