# JSON Templates for response formatting
json_template:
  # Basic template with minimal metadata
  default:
    response: null  # Will be filled with model response
    metadata:
      model: null   # Will be filled with model name
      timestamp: null  # Will be filled with current timestamp
  
  # Detailed template with structured response and additional metadata
  detailed:
    response:
      content: null  # Main content
      summary: null  # Summary (if model provides)
    metadata:
      model: null  # Will be filled with model name
      timestamp: null  # Will be filled with current timestamp
      processing_time: null  # Will be filled if available
  
  # Template for comparing multiple models
  comparison:
    results:
      main_response: null  # Primary model response
      alternatives: []  # Alternative model responses can be stored here
    metadata:
      primary_model: null
      comparison_models: []
      timestamp: null
  
  # Template for structured data responses
  structured_data:
    data:
      title: null
      sections: []
      key_points: []
    metadata:
      model: null
      timestamp: null
      format_version: "1.0"